{
 "title": "Dummy puller dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Histogram panel",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dummy_puller_histogram_bucket" }
   ]
  },
  {
   "title": "Summary panel",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dummy_puller_summary_count" },
    { "expr": "dummy_puller_summary_sum" }
   ]
  },
  {
   "title": "Counter and gauge panel",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dummy_puller_gauge" },
    { "expr": "dummy_puller_counter" }
   ]
  }
 ]
}